name: kinsta
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  flutter_svg:

flutter:
  fonts:
    - family: Instagram
      fonts:
        - asset: fonts/Instagram.ttf

  uses-material-design: true
  assets:
    - assets/vectors/
    - assets/images/

